{% set name = "hagerstrand" %}
{% set version = "0.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: cb23474aa6cdc91d3097d0319bbe654c747db0342f07a1d8cc27f30ec2780888

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - folium
    - ipyleaflet
    - pandas
    - pyshp
    - geopandas
    - earthengine-api
    - scikit-learn
    - shapely
    - python >=3.6

test:
  imports:
    - hagerstrand

about:
  home: "https://github.com/jimmy-feng/hagerstrand"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for an interactive space-time Geographic Information System (GIS)"
  doc_url: https://jimmy-feng.github.io/hagerstrand
  dev_url: https://github.com/jimmy-feng/hagerstrand

extra:
  recipe-maintainers:
    - jimmy-feng
